temp = input('Digite algo: ')
print('{}: classe {}'.format(temp, type(temp)))
print()
print('{}: é alphanumerico? {}'.format(temp, temp.isalnum()))
print()
print('{}: é decimal? {}'.format(temp, temp.isdecimal()))
print()
print('{}: é lowercase? {}'.format(temp, temp.islower()))
print()
print('{}: é uppercase? {}'.format(temp, temp.isupper()))
print()
print('{}: é numerico? {}'.format(temp, temp.isnumeric()))
